# Generated by Django 5.0.4 on 2024-05-18 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0006_alter_custom_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(help_text="Enter phone number in the format '+2519xxxxxxxx' or '+2517xxxxxxxx'.", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+2519xxxxxxxx' or '+2517xxxxxxxx'.", regex='^\\+251(9|7)\\d{8}$')]),
        ),
    ]
