# Generated by Django 5.0.4 on 2024-05-19 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0007_custom_user_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(help_text="Enter phone number in the format '+2519xxxxxxxx' or '+2517xxxxxxxx'.", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+2519xxxxxxxx' or '+2517xxxxxxxx'.", regex='^\\+251(9|7)\\d{8}$')]),
        ),
    ]
