# Generated by Django 5.0.4 on 2024-06-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0009_alter_custom_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
