# Generated by Django 5.0.4 on 2024-06-09 13:15

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0011_remove_custom_user_city_alter_custom_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='country',
            field=django_countries.fields.CountryField(default='ET', max_length=2),
        ),
    ]
