# Generated by Django 5.0.4 on 2024-07-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0012_alter_custom_user_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='telegram_username',
            new_name='telegram_user_id',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('customer', 'Customer'), ('admin', 'Admin'), ('receptionist', 'Receptionist')], default='customer', max_length=20),
        ),
    ]
