# Generated by Django 5.0.4 on 2024-08-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0013_rename_telegram_username_custom_user_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={},
        ),
    ]
