# Generated by Django 5.0.4 on 2024-09-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0014_alter_custom_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
