# Generated by Django 5.0.4 on 2025-04-18 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0015_alter_custom_user_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(help_text="Enter phone number in the format '+233xxxxxxxx'.", max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+233xxxxxxxx'.", regex='^\\+233(5|2)\\d{8}$')]),
        ),
    ]
