# Generated by Django 5.0.4 on 2024-05-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('yenepay', 'YenePay')], max_length=20),
        ),
    ]
