# Generated by Django 5.0.4 on 2024-05-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_booking_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
