# Generated by Django 5.0.4 on 2024-05-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
