# Generated by Django 5.0.4 on 2024-05-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
