# Generated by Django 5.0.4 on 2024-05-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_booking_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
