# Generated by Django 5.0.4 on 2024-05-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
