# Generated by Django 5.0.4 on 2024-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_booking_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extended_days',
            field=models.IntegerField(default=0),
        ),
    ]
