# Generated by Django 5.0.4 on 2024-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_booking_extended_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extended_days',
        ),
        migrations.AddField(
            model_name='booking',
            name='extended_check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
