# Generated by Django 5.0.4 on 2024-06-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_remove_booking_extended_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('paypal', 'PayPal')], default='chapa', max_length=20),
        ),
    ]
