# Generated by Django 5.0.4 on 2024-06-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_extend_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
