# Generated by Django 5.0.4 on 2024-07-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_booking_booking_extend_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
