# Generated by Django 5.0.4 on 2024-07-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=True),
        ),
    ]
