# Generated by Django 5.0.4 on 2024-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_booking_checked_in_booking_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('paypal', 'PayPal'), ('cash', 'Cash')], default='chapa', max_length=20),
        ),
    ]
