# Generated by Django 5.0.4 on 2024-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0026_alter_room_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/receipts/'),
        ),
    ]
