# Generated by Django 5.0.4 on 2024-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0028_booking_email2_booking_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
