# Generated by Django 5.0.4 on 2025-04-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0029_category_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
