# Generated by Django 5.0.4 on 2025-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0032_remove_booking_id_image_booking_wants_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meal_preferences',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wants_cleaning_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='wants_cooking_service',
            field=models.BooleanField(default=False),
        ),
    ]
