# Generated by Django 5.0.4 on 2024-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spabooking',
            name='full_name',
        ),
        migrations.AddField(
            model_name='spabooking',
            name='for_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='spabooking',
            name='for_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spabooking',
            name='for_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spabooking',
            name='for_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
