# Generated by Django 5.0.4 on 2024-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spa', '0003_spaservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spapackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
