# Generated by Django 5.0.4 on 2024-08-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spa', '0004_spapackage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spapackage',
            name='services',
        ),
    ]
