# Generated by Django 5.0.4 on 2024-08-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spa', '0006_alter_spabooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spapayment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/receipts/'),
        ),
    ]
