# Generated by Django 5.0.4 on 2024-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spa', '0007_spapayment_receipt_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='spabooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
