# Generated by Django 5.0.4 on 2024-08-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spa', '0008_spabooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spapayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
