# Generated by Django 5.0.4 on 2024-08-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/social_media/'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/social_media/'),
        ),
    ]
