# Generated by Django 5.0.4 on 2024-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_socialmediapost_image_socialmediapost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
