# Generated by Django 5.0.4 on 2024-08-25 20:00

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_alter_socialmediapost_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='platform',
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], default='telegram', max_length=29),
        ),
    ]
