# Generated by Django 5.0.4 on 2024-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_remove_socialmediapost_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='video',
        ),
    ]
