# Generated by Django 5.0.4 on 2024-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_remove_socialmediapost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='facebbok_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='instagram_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='telegram_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='x_post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
