# Generated by Django 5.0.4 on 2024-08-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_rename_facebbok_post_id_socialmediapost_facebook_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='instagram_post_id',
            new_name='instagram_message_id',
        ),
    ]
