# Generated by Django 5.0.4 on 2024-08-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_rename_instagram_post_id_socialmediapost_instagram_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='instagram_message_id',
            new_name='instagram_post_id',
        ),
        migrations.RenameField(
            model_name='socialmediapost',
            old_name='telegram_post_id',
            new_name='telegram_message_id',
        ),
    ]
