# Generated by Django 5.0.4 on 2024-08-27 21:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0009_rename_instagram_message_id_socialmediapost_instagram_post_id_and_more'),
    ]

    operations = [
        # Make necessary field alterations or remove them if not needed anymore
    ]
