# Generated by Django 5.0.4 on 2024-08-27 21:27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_alter_socialmediapost_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='message',
            field=models.TextField(),  # Replace with the desired field type
        ),
    ]
