# Generated by Django 5.0.4 on 2024-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0011_alter_socialmediapost_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='message',
            field=models.TextField(),
        ),
    ]
