# Generated by Django 5.0.4 on 2024-06-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='features',
        ),
    ]
