# Generated by Django 5.0.4 on 2024-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_membershipplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
