# Generated by Django 5.0.4 on 2024-06-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_membership_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
