# Generated by Django 5.0.4 on 2024-06-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_membership_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
