# Generated by Django 5.0.4 on 2024-06-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_membership_for_first_name_membership_for_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membership',
            name='for_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
