# Generated by Django 5.0.4 on 2024-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('paypal', 'PayPal')], default='chapa', max_length=20),
        ),
    ]
