# Generated by Django 5.0.4 on 2024-07-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_membership_full_name_alter_membership_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='full_name',
        ),
    ]
