# Generated by Django 5.0.4 on 2024-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/receipts/'),
        ),
    ]
