# Generated by Django 5.0.4 on 2024-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/hall_images/'),
        ),
    ]
