# Generated by Django 5.0.4 on 2024-06-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0003_category_rename_price_per_hour_hall_price_per_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Hall_Category',
        ),
    ]
