# Generated by Django 5.0.4 on 2024-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0004_rename_category_hall_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
