# Generated by Django 5.0.4 on 2024-07-04 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0005_hall_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hall_booking',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(6, 0), null=True),
        ),
    ]
