# Generated by Django 5.0.4 on 2024-07-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0006_hall_booking_end_time_hall_booking_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='price_per_day',
            new_name='price_per_hour',
        ),
    ]
