# Generated by Django 5.0.4 on 2024-07-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0007_rename_price_per_day_hall_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='hall_booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
