# Generated by Django 5.0.4 on 2024-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0010_hall_booking_full_name_hall_booking_occupied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall_payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa'), ('paypal', 'PayPal'), ('cash', 'Cash')], default='chapa', max_length=20),
        ),
    ]
